<?php

/**
 * BaseDmTalkMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $room_id
 * @property string $speaker_name
 * @property string $text
 * @property integer $to_speaker_id
 * @property DmTalkRoom $Room
 * @property DmTalkSpeaker $ToSpeaker
 * 
 * @method integer       getRoomId()        Returns the current record's "room_id" value
 * @method string        getSpeakerName()   Returns the current record's "speaker_name" value
 * @method string        getText()          Returns the current record's "text" value
 * @method integer       getToSpeakerId()   Returns the current record's "to_speaker_id" value
 * @method DmTalkRoom    getRoom()          Returns the current record's "Room" value
 * @method DmTalkSpeaker getToSpeaker()     Returns the current record's "ToSpeaker" value
 * @method DmTalkMessage setRoomId()        Sets the current record's "room_id" value
 * @method DmTalkMessage setSpeakerName()   Sets the current record's "speaker_name" value
 * @method DmTalkMessage setText()          Sets the current record's "text" value
 * @method DmTalkMessage setToSpeakerId()   Sets the current record's "to_speaker_id" value
 * @method DmTalkMessage setRoom()          Sets the current record's "Room" value
 * @method DmTalkMessage setToSpeaker()     Sets the current record's "ToSpeaker" value
 * 
 * @package    Acme
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDmTalkMessage extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_talk_message');
        $this->hasColumn('room_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('speaker_name', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('text', 'string', 64000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64000,
             ));
        $this->hasColumn('to_speaker_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmTalkRoom as Room', array(
             'local' => 'room_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('DmTalkSpeaker as ToSpeaker', array(
             'local' => 'to_speaker_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}