<?php

/**
 * BaseDmTalkRoom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property Doctrine_Collection $Speakers
 * @property Doctrine_Collection $Messages
 * 
 * @method string              getCode()     Returns the current record's "code" value
 * @method Doctrine_Collection getSpeakers() Returns the current record's "Speakers" collection
 * @method Doctrine_Collection getMessages() Returns the current record's "Messages" collection
 * @method DmTalkRoom          setCode()     Sets the current record's "code" value
 * @method DmTalkRoom          setSpeakers() Sets the current record's "Speakers" collection
 * @method DmTalkRoom          setMessages() Sets the current record's "Messages" collection
 * 
 * @package    Acme
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDmTalkRoom extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_talk_room');
        $this->hasColumn('code', 'string', 8, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DmTalkSpeaker as Speakers', array(
             'local' => 'id',
             'foreign' => 'room_id'));

        $this->hasMany('DmTalkMessage as Messages', array(
             'local' => 'id',
             'foreign' => 'room_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}