<?php

/**
 * BaseArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $extract
 * @property clob $body
 * @property integer $image
 * @property integer $author
 * @property boolean $is_active
 * @property DmMedia $Image
 * @property DmUser $Author
 * 
 * @method string  getTitle()     Returns the current record's "title" value
 * @method string  getExtract()   Returns the current record's "extract" value
 * @method clob    getBody()      Returns the current record's "body" value
 * @method integer getImage()     Returns the current record's "image" value
 * @method integer getAuthor()    Returns the current record's "author" value
 * @method boolean getIsActive()  Returns the current record's "is_active" value
 * @method DmMedia getImage()     Returns the current record's "Image" value
 * @method DmUser  getAuthor()    Returns the current record's "Author" value
 * @method Article setTitle()     Sets the current record's "title" value
 * @method Article setExtract()   Sets the current record's "extract" value
 * @method Article setBody()      Sets the current record's "body" value
 * @method Article setImage()     Sets the current record's "image" value
 * @method Article setAuthor()    Sets the current record's "author" value
 * @method Article setIsActive()  Sets the current record's "is_active" value
 * @method Article setImage()     Sets the current record's "Image" value
 * @method Article setAuthor()    Sets the current record's "Author" value
 * 
 * @package    Acme
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticle extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article');
        $this->hasColumn('title', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('extract', 'string', 2000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2000,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('image', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('author', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmMedia as Image', array(
             'local' => 'image',
             'foreign' => 'id'));

        $this->hasOne('DmUser as Author', array(
             'local' => 'author',
             'foreign' => 'id'));

        $dmsortable0 = new Doctrine_Template_DmSortable();
        $dmcommentable0 = new Doctrine_Template_DmCommentable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'extract',
              2 => 'body',
              3 => 'is_active',
             ),
             ));
        $timestampable1 = new Doctrine_Template_Timestampable();
        $i18n0->addChild($timestampable1);
        $dmversionable1 = new Doctrine_Template_DmVersionable();
        $i18n0->addChild($dmversionable1);
        $this->actAs($dmsortable0);
        $this->actAs($dmcommentable0);
        $this->actAs($i18n0);
    }
}