<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('dm_comment', 'record_model', 'string', '254', array(
             'notnull' => '1',
             ));
        $this->changeColumn('dm_comment', 'author_email', 'string', '254', array(
             'notnull' => '',
             ));
        $this->changeColumn('dm_comment', 'author_website', 'string', '254', array(
             'notnull' => '',
             'extra' => 'link',
             ));
        $this->changeColumn('dm_comment', 'body', 'clob', '', array(
             'notnull' => '',
             ));
        $this->changeColumn('dm_comment', 'is_active', 'boolean', '25', array(
             'notnull' => '',
             'default' => '1',
             ));
    }

    public function down()
    {

    }
}