<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('article', 'article_image_dm_media_id', array(
             'name' => 'article_image_dm_media_id',
             'local' => 'image',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             ));
        $this->createForeignKey('article', 'article_author_dm_user_id', array(
             'name' => 'article_author_dm_user_id',
             'local' => 'author',
             'foreign' => 'id',
             'foreignTable' => 'dm_user',
             ));
        $this->createForeignKey('article_translation', 'article_translation_id_article_id', array(
             'name' => 'article_translation_id_article_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'article',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('article_translation_version', 'article_translation_version_id_article_translation_id', array(
             'name' => 'article_translation_version_id_article_translation_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'article_translation',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('article', 'article_image', array(
             'fields' => 
             array(
              0 => 'image',
             ),
             ));
        $this->addIndex('article', 'article_author', array(
             'fields' => 
             array(
              0 => 'author',
             ),
             ));
        $this->addIndex('article_translation', 'article_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('article_translation_version', 'article_translation_version_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('article', 'article_image_dm_media_id');
        $this->dropForeignKey('article', 'article_author_dm_user_id');
        $this->dropForeignKey('article_translation', 'article_translation_id_article_id');
        $this->dropForeignKey('article_translation_version', 'article_translation_version_id_article_translation_id');
        $this->removeIndex('article', 'article_image', array(
             'fields' => 
             array(
              0 => 'image',
             ),
             ));
        $this->removeIndex('article', 'article_author', array(
             'fields' => 
             array(
              0 => 'author',
             ),
             ));
        $this->removeIndex('article_translation', 'article_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('article_translation_version', 'article_translation_version_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}