<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/22 07:05:55

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=acme;',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
