<?php
// auto-generated by sfSimpleYamlConfigHandler
// date: 2012/02/22 07:05:58
return array (
  'dmWidgetContent' => 
  array (
    'title' => 
    array (
      'cache' => 'static',
    ),
    'link' => 
    array (
      'cache' => true,
    ),
    'text' => 
    array (
      'cache' => true,
    ),
    'image' => 
    array (
      'cache' => true,
    ),
    'galleryGrid' => 
    array (
      'cache' => true,
    ),
    'nivoGallery' => 
    array (
      'cache' => true,
    ),
    'gallery' => 
    array (
      'cache' => true,
    ),
  ),
  'dmWidgetNavigation' => 
  array (
    'breadCrumb' => 
    array (
      'cache' => true,
    ),
    'menu' => 
    array (
      'cache' => true,
    ),
  ),
  'dmWidgetSearch' => 
  array (
    'form' => 
    array (
      'cache' => true,
      'public_name' => 'Search form',
    ),
    'results' => 
    array (
      'cache' => false,
      'public_name' => 'Search results',
    ),
  ),
  'dmWidgetTwitter' => 
  array (
    'search' => 
    array (
      'cache' => false,
      'public_name' => 'Twitter search',
    ),
    'timeline' => 
    array (
      'cache' => false,
      'public_name' => 'Twitter timeline',
    ),
  ),
);
